### ISSUE TITLE
Use Workflow Templates for Release and Pull Request Builds

### ISSUE THREAD

**Issue by ThisaruGuruge** [ballerina-platform/ballerina-library#3581]
**Description:**
$Subject.

To use the workflow templates, follow these examples:

The `publish-release.yml` workflow:

```yaml
name: Publish Release
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ stdlib-release-pipeline ]
jobs:
  release-package:
    name: Release Package
    uses: ballerina-platform/ballerina-standard-library/.github/workflows/release-package-template.yml@main
    with:
      package-org: "ballerina" # Required
      package-name: "graphql" # Required
      additional-build-flags: "-x :graphql-examples:build" # Optional - Used for the step `Build without Tests`
      additional-publish-flags: "" # Optional - Used for the step `Publish Package`
```

The `pull-request.yml`:

```yaml
name: Pull Request Build
on: pull_request
jobs:
  pull-request-build:
    name: Pull Request Build
    uses: ballerina-platform/ballerina-standard-library/.github/workflows/pull-request-build-template.yml@main
    with:
      additional-ubuntu-test-flags: "-P disable=disabled_on_ubuntu" # Optional - Used for running/skipping a group of tests in Ubuntu
      additional-windows-test-flags: "-P disable=disabled_on_windows" # Optional - Used for running/skipping a group of tests in Windows
```

Module List:

- [ ] constraint
- [ ] io
- [ ] java.arrays
- [ ] regex
- [ ] time
- [ ] url
- [ ] xmldata
- [ ] crypto
- [ ] log
- [ ] os
- [ ] protobuf
- [ ] random
- [ ] serdes
- [ ] task
- [ ] xslt
- [ ] cache
- [ ] file
- [ ] ftp
- [ ] mime
- [ ] tcp
- [ ] udp
- [ ] uuid
- [ ] auth
- [ ] email
- [ ] jwt
- [ ] oauth2
- [ ] http
- [ ] grpc
- [ ] websocket
- [ ] websub
- [ ] websubhub
- [ ] graphql
- [ ] sql
- [ ] nats
- [ ] stan
- [ ] kafka
- [ ] rabbitmq
- [ ] java.jdbc
- [ ] mssql
- [ ] mysql
- [ ] oracledb
- [ ] postgresql
