### ISSUE TITLE
Create anydata fields for object properties with custom data types

### ISSUE THREAD

**Issue by aneeshafedo** [ballerina-platform/ballerina-library#4872]
**Description:**
In the current client generation, when an unknown data type is defined in a schema, we return an error saying 

`Unsupported OAS data type` 

The better approach would be to generate those fields with `anydata` type without breaking the workflow. 

Sample OpenAPI: 

```yaml
BookedRooms:
      title: BookedRooms
      type: object
      properties: 
        roomType:
          type: xxx
        name: 
          type: string
```

Here the type is an unknown type `xxx`. 

Please also check whether we are returning this error in any other cases where we can generate with `anydata` type. 

Affected version: 2201.8.0

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
