### ISSUE TITLE
Incomplete OpenAPI spec generation when defined Ballerina type with Enum

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#5123]
**Description:**
Ballerina Code 
```ballerina
import ballerina/http;

enum Action {
    GET,
    POST,
    PUT,
    DELETE,
    PATCH
}

type Name Action;
service /payloadV on new http:Listener(9090) {
    resource function post reservation(OrderType ird, @http:Payload Link link) returns Name {
        return POST;
    }
}
```
Generated OpenAPI spec
```
...
components:
  schemas:
    Order:
      required:
      - rel
      type: object
      properties:
        rel:
          type: string
        actions:
          type: string
          enum:
          - custom size
          - Half "Portion"
          - full
    Name:
      oneOf:
      - {}
      - {}
      - {}
      - {}
      - {}
```
Fix can be added after these https://github.com/ballerina-platform/ballerina-lang/issues/38179#issuecomment-1649395889
