### ISSUE TITLE
Overlapping object properties in `allOf` generates duplicate fields.

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#5722]
**Description:**
When there are overlapping properties of objects referred to under `allOf` has to override the incoming property. Here instead duplicate fields are generated.

**Steps to reproduce:**
Check this example:
```yaml
components:
  schemas:
    Cat:
      allOf:
        - type: object
          properties:
            name:
              type: string
            age:
              type: integer
        - type: object
          properties:
            hunts:
              type: boolean
            age:
              type: integer
```
for the above OAS(not a complete), the below record is gettings generated,
```ballerina
public type Cat record {
    string name?;
    int age?;
    boolean hunts?;
    int age?;
};
```
instead of,
```ballerina
public type Cat record {
    string name?;
    int age?;
    boolean hunts?;
};
```
**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
