### ISSUE TITLE
Restructure Ballerina resource path parameters to OAS module

### ISSUE THREAD

**Issue by SachinAkash01** [ballerina-platform/ballerina-library#5816]
**Description:**

Need to restructure the code base of resource path parameter mapping from Ballerina to OpenAPI specification.
Parent: #5055 

When the code is properly restructured, the resource path parameters are reflected in the OpenAPI specification as follows,

Sample Ballerina code:
```ballerina
# Description of the function.
#
# + title - Title of the album
# + return - Return description
resource function get albums/[string title]() {}
```

OpenAPI specification:
```yaml
paths:
  /albums/{title}:
      get:
        summary: Description of the function
        operationId: getSongsAlbumId
        parameters:
        - name: title
          in: path
          description: Title of the album
          required: true
          schema:
            type: string
```

**Rest parameters in the resource path:**

Ballerina supports rest parameters. There cannot be another parameter after a rest parameter in the resource path.
Utilizing rest parameters in the path of a resource function acts as a list. For example:
```ballerina
resource function get users/[int... id]() {}
```
This allows us to send a request like:
`GET users/id1/id2/id3`

In the resulting URL, these parameters are concatenated with `%2F` (encoded value for `/`), and it looks like:
`http://{hostName}:{port}/users/id1%2Fid2%2Fid3`

**Parameter serialization** is used in OpenAPI specification to support arrays and objects in operation parameters (path, query, header, and cookie) and lets you specify how these parameters should be serialized. The serialization method is defined by the `style` and `explode` keywords.

After having some discussions, we decided to omit the mapping of the entire operation for now if there is a rest parameter in the resource path and provide users with a warning since we cannot properly reflect rest parameters in the OpenAPI specification!
> Note: we can map the operation without path parameters when there is a rest parameter in the resource path, but then the OpenAPI spec will show incorrect information regarding that operation.
