### ISSUE TITLE
Nillable Enum Types Result in Incorrect Record Field Generation

### ISSUE THREAD

**Issue by AzeemMuzammil** [ballerina-platform/ballerina-library#5902]
**Description:**
When using the OpenAPI client generator tool, there is an issue with how nillable enum types are handled.  When the enum type is marked as nillable and not required in the OpenAPI schema, the corresponding Ballerina record's field is generated as only optional, instead of both optional and nullable.

Refer to the below example:
```yaml
components:
  schemas:
    Task:
      type: object
      properties:
        title:
          type: string
          description: The title of the task
        priority:
          type: string
          description: The priority of the task
          enum:
            - Low
            - Medium
            - High
          nullable: true
```
For the above OpenAPI Spec, generated record looks like below,
```ballerina
public type Task record {
    # The title of the task
    string title?;
    # The priority of the task
    "Low"|"Medium"|"High" priority?;
};
```
But the expected record should look as below,
```ballerina
public type Task record {
    # The title of the task
    string title?;
    # The priority of the task
    "Low"|"Medium"|"High"? priority?;
};
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
