### ISSUE TITLE
Openapi generated client should have an easier way to configure variables in serviceUrl

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-library#6075]
**Description:**
Currently for this schema,
```yaml
servers:
  - url: https://{host}:{port}/sap/opu/odata/sap/API_SALES_ORDER_SRV
    variables:
      host:
        default: ''
      port:
        default: ''
```

The generated client has following parameters,
```ballerina
public isolated function init(ConnectionConfig config, string serviceUrl = "https://:/sap/opu/odata/sap/API_SALES_ORDER_SRV") returns error? {
}
```

The above is not user friendly as the user has to ovveride the entire serviceUrl for giving host and port.
```ballerina
public isolated function init(ConnectionConfig config, string host = "", port = "", string serviceUrl = "https://:/sap/opu/odata/sap/API_SALES_ORDER_SRV") returns error? {
}
```
IMO the above definition will be much userfriendly,

Here we may have to have some conventions, 
1. If service url param is given, the variables will be not be used and service url will be taken as the final value. 
2. If the variable values are ovveridden then they should be used to template the serviceURl

The conventions need to be validated as these depend on the fact we can idenify of the user has provided values to the function or is it the default value.
