### ISSUE TITLE
Write a sample ballerina application to integrate with Solace event broker using JMS

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-library#6199]
**Description:**
> $subject

Solace Event Broker - https://solace.com/products/event-broker/

**Comment by ayeshLK** [comment]
Following sample code could be use to connect to the Solace cloud:

### Ballerina.toml

```toml
[[platform.java11.dependency]]
groupId = "com.solacesystems"
artifactId = "sol-jms"
version = "10.22.0" 
```

### main.bal

```ballerina
    jms:Connection connection = check new (
        initialContextFactory = "com.solacesystems.jndi.SolJNDIInitialContextFactory",
        providerUrl = "<provider-url>",
        connectionFactoryName = "<connection-factory>",
        properties = {
            "Solace_JMS_VPN": "<cluster name>",
            "java.naming.security.principal": "<user-name>",
            "java.naming.security.credentials": "<password>"
        }
    );
```
