### ISSUE TITLE
Fix payload binding when response media type has `application/json; charset=utf-8`

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#6343]
**Description:**
example OAS:
```yaml
"/catalog/datasets/{dataset_id}/records": {
        "get": {
          "summary": "Query dataset records",
          "operationId": "getRecords",
          "tags": [
            "Dataset"
          ],
          "description": "Perform a query on dataset records.",
          ...
          "responses": {
            "200": {
              "description": "Records",
              "content": {
                "application/json; charset=utf-8": {
                  "schema": {
                    "$ref": "#/components/schemas/results-v2.1"
                  },
                  "examples": {
                    "records": {
                      "$ref": "#/components/examples/records-v2.1"
                    },
                    "group_by_country": {
                      "$ref": "#/components/examples/group_by_country-v2.1"
                    }
                  }
                }
              }
            },
```
