### ISSUE TITLE
Openapi tool source code not getting regenerated after removing the generated code.

### ISSUE THREAD

**Issue by gayaldassanayake** [ballerina-platform/ballerina-library#6591]
**Description:**
In openapi automate client generation, if the code is generated once with `bal build`, that code is deleted and `bal build` run again, the code is not getting generated again. However if we delete the target dir (which contains a cache for openapi tool), the generation works fine.

**Steps to reproduce:**
1. In a new ballerina project add an openapi tool entry.
   ``` toml
    [[tool.openapi]]
    id = "oa1"
    filePath="service.yaml"
    targetModule="oa1_target"
    options.mode = "client"
   ```
2. Run `bal build`. This will create both `target` dir and the `generated` dir.
3. Delete only the `generated` dir
4. Re-run `bal build`

**Affected Versions:**
2201.9.0

**OS, DB, other environment details and versions:**
MacOS

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
