### ISSUE TITLE
h1-h2 load test hanging after sometime

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-library#6663]
**Description:**
When using a http1 client with a passthrough which has a h2 client to connect to a backend, the requests hang after some time. Note that both the services are ballerina. The http1 client used is jmeter.

We can use the following docker-compose to recreate this.
```
services:
  bal-passthrough-service:
    image: dilansachi/balpassthroughservices:latest
    network_mode: "host"
  bal-backend-service:
    image: dilansachi/backend_bal:latest
    network_mode: "host"
```
