### ISSUE TITLE
Resolve conflicts when generating Ballerina friendly names from the OpenAPI specification 

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-library#6897]
**Description:**

There can be conflicts when we try to change the name of a parameter/type/property in the OpenAPI specification using the `--use-sanitized-oas` option. Those conflicts should be resolved properly.

For example, consider the following components schema:
```yaml
components:
  schemas:
    response:
      required:
      - value1
      type: object
      properties:
        value1:
          type: string
    Response:
      required:
      - value1
      - value2
      type: object
      properties:
        value1:
          type: number
        value2:
          type: string
```
       
The generated name for both `Response` and `response` is `Response`. This will not return a compiler error but one record will overwrite the other which is wrong.

**Describe your task(s)**

- [ ] Propose a way to resolve the conflicts
- [ ] Implement name conflict resolver in the name proposer component
