### ISSUE TITLE
Add `jsondata` name attribute mapping in the OpenAPI generation

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-library#7014]
**Description:**

With the implementation of this [proposal](https://github.com/ballerina-platform/ballerina-library/issues/6747), the data-binding will be supported with the `jsondata` name attribute in HTTP. This has an impact on the generated OpenAPI specification from the service.

Consider the following type definition:
```bal
public type Album record {|
    string artist;
    @jsondata:Name {value: "_id"}
    string id;
    string title;
|};
```

This is currently mapped to the following schema:
```yaml
Album:
  required:
    - id
    - artist
    - title
  type: object
  properties:
    id:
      type: string
    title:
      type: string
    artist:
      type: string
  additionalProperties: false
```

But according to the `jsondata` annotation, the field `id` should be considered as `_id`. So the new schema definition should look like this:
```yaml
Album:
  required:
    - _id
    - artist
    - title
  type: object
  properties:
    _id:
      type: string
    title:
      type: string
    artist:
      type: string
  additionalProperties: false
```

**Describe your task(s)**

- [x] Add `jsondata` name attribute mapping in the generated schema name
