### ISSUE TITLE
Should be able to define container ports

### ISSUE THREAD

**Issue by raj-rajaratnam** [ballerina-platform/ballerina-library#7173]
**Description:**
Currently container ports are defined from Service annotations. Ballerina core exposes some ports (e.g Prometheus) for which we don't have an endpoint defined in our ballerina program (hence we can't define service annotations). So we should be able to define these kind of ports in Kubernetes:Deployment annotation. 

```
ports: 
- containerPort: 8280
   name: http 
- containerPort: 9797
   name: prometheus 
```
