### ISSUE TITLE
Add HTTP default listener

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-library#7514]
### Description

Add a default listener implementation for HTTP, which will be used as a starting point for any service implementation and this can be used for centralised deployment where multiple services can be attached to this same listener.

### Version

Ballerina Swan Lake Update 11

**Comment by TharmiganK** [comment]
Example usage:
```ballerina
import ballerina/http;

listener http:Listener httpListener = http:getDefaultListener();

service /api/v1 on httpListener {

    resource function get greeting() returns string {
        return "Hello, World from Service 1!";
    }
}
```

The default port and listener configuration can be changed in the `Config.toml` as follows:
```toml
[ballerina.http]
defaultListenerPort = 8080

[ballerina.http.defaultListenerConfig]
httpVersion = "1.1"

[ballerina.http.defaultListenerConfig.secureSocket.key]
path = "resources/certs/ballerinaKeystore.p12"
password = "ballerina"
```
