### ISSUE TITLE
Generated AsyncAPI Spec Missing Remote Function Details in WebSocket Service

### ISSUE THREAD

**Issue by chathushkaayash** [ballerina-platform/ballerina-library#7669]
### Description

I attempted to generate an AsyncAPI specification for the following WebSocket sample code using Ballerina AsyncAPI Tool:

```ballerina
import ballerina/websocket;

@websocket:ServiceConfig {
    dispatcherKey: "event"
}
service /websockets on new websocket:Listener(9090) {
    resource function get .() returns MyGqlSubService {
        return new MyGqlSubService();
    }
}

service class MyGqlSubService {
    *websocket:Service;

    remote function onConnectionInit(string chatMessage) returns ConnectionAck|error {
        ConnectionAck connAck = { event: "connection_ack", payload: "{}" };
        return connAck;
    }

    remote function onSubscription() returns stream<Next|Complete> {
        Next[] next = [
            { id: "1", event: "data", payload: "{}" },
            { id: "2", event: "data", payload: "{}" },
            { id: "3", event: "data", payload: "{}" }
        ];
        return next.toStream();
    }

    remote function onMessage(websocket:Caller caller, string chatMessage) returns error? {
        return caller->close(4408, "Connection initialisation timeout");
    }
}

type Next record {|
    string id;
    string event;
    string payload;
|};

type Complete record {|
    string id;
    string event;
|};

type ConnectionAck record {|
    string event;
    string payload;
|};
```

## Generated AsyncAPI specification
```yaml
asyncapi: 2.5.0
info:
  title: Websockets
  version: 0.0.0
servers:
  development:
    url: "{server}:{port}/websockets"
    protocol: ws
    protocolVersion: "13"
    variables:
      server:
        default: ws://localhost
      port:
        default: "9090"
channels:
  /: {}
components: {}
x-dispatcherKey: event
```
## Problem
The generated AsyncAPI specification does not include any details about the remote functions such as `onConnectionInit`, `onSubscription`, or `onMessage`.

## Expected Behavior:
The generated AsyncAPI specification should include relevant details for the WebSocket service's remote functions, describing their payloads, and return types.

### Steps to Reproduce

1. Use the provided WebSocket service code.
2. Generate the AsyncAPI spec.
3. Observe that the generated spec does not include details about the remote functions.

### Version

Ballerina 2201.11.0
